@section('head')
<style>
    .customer-page-actions,.customer-filter-actions,.account-badges,.detail-actions{display:flex;align-items:center;gap:8px;flex-wrap:wrap}
    .customer-alert{margin-bottom:14px;padding:12px 14px;border:1px solid;border-radius:8px;font-size:13px;font-weight:700}.customer-alert.success{color:#245f35;border-color:#bfe3c8;background:#edf9f0}.customer-alert.error{color:#8f3122;border-color:#f0bcb1;background:#fff1ee}
    .customer-stats{display:grid;grid-template-columns:repeat(5,minmax(0,1fr));gap:10px;margin-bottom:10px}.customer-stat{display:grid;gap:8px;min-height:84px;padding:13px;border:1px solid var(--admin-line);border-radius:8px;background:#fff;color:var(--admin-ink)}.customer-stat:hover{border-color:#9fc4a5;box-shadow:0 7px 18px rgba(28,70,44,.07)}.customer-stat span{display:flex;align-items:center;gap:7px;color:var(--admin-subtle);font-size:11px;font-weight:750}.customer-stat span i{color:var(--admin-primary);font-size:16px}.customer-stat strong{align-self:end;font:800 24px 'Sora',sans-serif}
    .segment-strip{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:8px;margin-bottom:14px}.segment-link{display:flex;align-items:center;justify-content:space-between;min-height:42px;padding:8px 11px;border:1px solid #d8e4d6;border-radius:8px;background:#f9fbf8;color:#294735;font-size:12px;font-weight:750}.segment-link strong{display:grid;place-items:center;min-width:25px;height:25px;border-radius:50%;background:#edf4e8;color:var(--admin-primary)}.segment-link.active,.segment-link:hover{border-color:#9fc4a5;background:#f0f7ed}
    .customer-filter-grid{display:grid;grid-template-columns:minmax(220px,1.5fr) repeat(3,minmax(130px,.75fr)) 90px auto;gap:10px;align-items:end}.customer-field{display:grid;gap:5px;min-width:0}.customer-field label{color:#42594b;font-size:11px;font-weight:750}.customer-input,.customer-select,.customer-textarea{width:100%;border:1px solid #cad8ca;border-radius:7px;padding:9px 10px;background:#fff;color:var(--admin-ink);font:inherit;font-size:12px}.customer-input,.customer-select{min-height:38px}.customer-textarea{min-height:94px;resize:vertical;line-height:1.5}.customer-input:focus,.customer-select:focus,.customer-textarea:focus{outline:2px solid rgba(31,122,74,.16);border-color:var(--admin-primary)}
    .customer-cell{display:flex;align-items:center;gap:9px;min-width:190px}.customer-avatar{display:grid;place-items:center;width:38px;height:38px;flex:0 0 38px;border-radius:50%;background:#eaf4e5;color:var(--admin-primary);font:800 15px 'Sora',sans-serif}.customer-cell>span:last-child,.customer-cell-stack{display:grid;gap:4px}.customer-cell small,.customer-cell-stack small{color:var(--admin-subtle);font-size:10px}.account-badges{gap:4px}.account-badge,.segment-badge{padding:4px 7px;border-radius:5px;font-size:10px;font-weight:800;white-space:nowrap}.account-badge.active,.account-badge.verified{color:#28623a;background:#e9f7ed}.account-badge.suspended,.account-badge.locked{color:#963d2d;background:#fff0ec}.account-badge.unverified{color:#7a5b00;background:#fff5d7}.segment-badge{color:#2b5f3a;background:#edf5e9}.customer-money{white-space:nowrap;color:#245f35}
    .customer-pager{display:flex;align-items:center;justify-content:space-between;gap:10px;flex-wrap:wrap;margin-top:12px;color:var(--admin-subtle);font-size:12px}.customer-pager>div{display:flex;gap:7px}.customer-pager a,.customer-pager .disabled{padding:7px 10px;border:1px solid var(--admin-line);border-radius:7px;background:#fff;font-weight:750}.customer-pager .disabled{opacity:.45}
    .customer-detail-grid{display:grid;grid-template-columns:minmax(0,1fr) 340px;gap:14px;align-items:start}.customer-detail-main,.customer-detail-side{display:grid;gap:14px;min-width:0}.customer-detail-side{position:sticky;top:88px}.customer-profile-head{display:flex;align-items:center;gap:12px}.customer-profile-avatar{display:grid;place-items:center;width:58px;height:58px;flex:0 0 58px;border-radius:50%;background:#e6f2df;color:var(--admin-primary);font:800 22px 'Sora',sans-serif;overflow:hidden}.customer-profile-avatar img{width:100%;height:100%;object-fit:cover}.customer-profile-head h2{margin:0 0 3px;font-size:18px}.customer-profile-head p{margin:0;color:var(--admin-subtle);font-size:12px}.customer-metrics{display:grid;grid-template-columns:repeat(5,minmax(0,1fr));gap:9px;margin-bottom:14px}.customer-metric{display:grid;gap:5px;min-height:76px;padding:11px;border:1px solid var(--admin-line);border-radius:8px;background:#fff}.customer-metric small{color:var(--admin-subtle);font-size:10px;font-weight:700}.customer-metric strong{align-self:end;font:800 18px 'Sora',sans-serif}.detail-form-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:10px}.detail-form-grid .span-2{grid-column:1/-1}.detail-list{display:grid;gap:9px}.detail-row{display:grid;grid-template-columns:120px minmax(0,1fr);gap:10px;padding-bottom:8px;border-bottom:1px solid #edf1ea;font-size:12px}.detail-row:last-child{padding-bottom:0;border-bottom:0}.detail-row>span:first-child{color:var(--admin-subtle)}.notice{padding:10px;border:1px solid #dce8d7;border-radius:7px;background:#f8fbf6;color:#405b46;font-size:11px;line-height:1.5}.notice.warning{border-color:#efd398;background:#fff9eb;color:#715000}.notice.danger{border-color:#efbdb3;background:#fff3f0;color:#8f3122}.account-action{display:grid;gap:8px;padding-top:10px;border-top:1px solid #edf1ea}.account-action:first-child{padding-top:0;border-top:0}.account-action h3{margin:0;font-size:13px}.account-action p{margin:0;color:var(--admin-subtle);font-size:11px;line-height:1.45}.account-action .btn{justify-content:center}.btn-danger{border-color:#efbdb3;background:#fff1ee;color:#9a3e2c}.address-list,.voucher-list,.security-list{display:grid;gap:8px}.address-item,.voucher-item,.security-item{display:grid;gap:5px;padding:10px;border:1px solid #dce6da;border-radius:7px;background:#fbfcfa;font-size:12px}.address-item-head,.voucher-item-head,.security-item-head{display:flex;justify-content:space-between;gap:8px;align-items:start}.address-item p,.voucher-item p,.security-item p{margin:0;color:var(--admin-subtle);font-size:11px;line-height:1.45}.mini-status{padding:3px 6px;border-radius:4px;background:#edf5e9;color:#2d663e;font-size:9px;font-weight:800;white-space:nowrap}.order-link{font-weight:800;color:var(--admin-primary)}
    @media(max-width:1200px){.customer-stats{grid-template-columns:repeat(3,1fr)}.customer-filter-grid{grid-template-columns:repeat(3,minmax(0,1fr))}.customer-detail-grid{grid-template-columns:1fr}.customer-detail-side{position:static}.customer-metrics{grid-template-columns:repeat(3,1fr)}}
    @media(max-width:760px){.customer-stats,.segment-strip,.customer-filter-grid,.customer-metrics,.detail-form-grid{grid-template-columns:1fr}.detail-form-grid .span-2{grid-column:auto}.detail-row{grid-template-columns:1fr;gap:3px}}
</style>
@endsection
